version: "3.8"
services:
  db:
    image: mysql:8
    env_file:     
      - ./docker/mysql/db.env    
    ports:
      - 3306:3306
    volumes:
      - ./docker-data/mysql/var/lib/mysql:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
  nginx:
    image: nginx:1.19
    ports:
      - 8080:8080
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./docker-data/nginx/var/log/nginx:/var/log/nginx
  app:
    image: ibrahim/app:0.1
    ports:
      - 3000:3000          


